version: "3"
services:
  nginx-lb:
    image: nginx:latest
    container_name: nginx-lb
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
    networks:
      - app-network

  app1:
    image: python:3.9-slim
    container_name: app1
    command: python3 -m http.server 8000
    volumes:
      - ./app:/app
    networks:
      - app-network

  app2:
    image: python:3.9-slim
    container_name: app2
    command: python3 -m http.server 8000
    volumes:
      - ./app:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
