version: "3.8"

services:
  app1:
    image: python:3.9-slim
    container_name: app1
    working_dir: /app
    volumes:
      - app-data:/app
    command: python3 -m http.server 8000
    networks:
      - app-network

  app2:
    image: python:3.9-slim
    container_name: app2
    working_dir: /app
    volumes:
      - app-data:/app
    command: python3 -m http.server 8000
    networks:
      - app-network

  nginx:
    image: nginx
    container_name: nginx-lb
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

volumes:
  app-data:

networks:
  app-network:
    driver: bridge
