version: '3'

services:
  app1:
    image: nginx
    container_name: app1
    volumes:
      - ./app1:/usr/share/nginx/html
    ports:
      - "8081:80"
      
  app2:
    image: nginx
    container_name: app2
    volumes:
      - ./app2:/usr/share/nginx/html
    ports:
      - "8082:80"

  nginx-lb:
    image: nginx
    container_name: nginx-lb
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app1
      - app2
