version: "3.8"

services:
  app1:
    image: python:3.9-slim
    container_name: app1
    working_dir: /app
    volumes:
      - app-data:/app
    command: python3 -m http.server 8000  # Serve on port 8000
    networks:
      - app-network

  app2:
    image: python:3.9-slim
    container_name: app2
    working_dir: /app
    volumes:
      - app-data:/app
    command: python3 -m http.server 8000  # Serve on port 8000
    networks:
      - app-network

  nginx:
    image: nginx
    container_name: nginx-lb
    ports:
      - "80:80"  # Expose port 80 on the host machine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount your Nginx configuration file
    networks:
      - app-network
    depends_on:
      - app1
      - app2

volumes:
  app-data:  # Define a persistent volume for both app1 and app2

networks:
  app-network:
    driver: bridge  # Use the bridge network for communication between containers
