version: '3.8'
  services:
    web:
      build: .
      ports:
        - "5000:5000"
      depends_on:
        - db

    db:
      image: mysql:8.0
      environment:
        MYSQL_ROOT_PASSWORD: rootpassword
        MYSQL_DATABASE: demo
      ports:
        - "3306:3306"
